---
#
# Include the shared gitlab CI definitions
#
include:
  - project: 'enterprisemodules/gitlab_ci'
    file: 'gitlab-ci.yml'

cache:
  key: "${CI_COMMIT_REF_SLUG}-vagrant"
  paths:
    - .vagrant/
  policy: pull-push
  when: always

  
setup RCU:
  stage: acceptance setup
  tags:
    - demo_check
  before_script:
    - vagrant prepare ml-rcudb
  script:
  - vagrant up ml-rcudb
  only:
    refs:
      - master

soa_12213_demo_check:
  extends: .demo_check
  variables:
    server: ml-soa12213n1
  script:
    - vagrant up ml-soa12213n1
    - vagrant up ml-soa12213n2
  after_script:
    - vagrant destroy ml-soa12213n1 ml-soa12213n2 --force

soa_12214_demo_check:
  extends: .demo_check
  variables:
    server: ml-soa12214n1
  script:
    - vagrant up ml-soa12214n1
    - vagrant up ml-soa12214n2
  after_script:
    - vagrant destroy ml-soa12214n1 ml-soa12214n2 --force

teardown RCU:
  stage: acceptance teardown
  tags:
    - demo_check
  script:
    - vagrant destroy ml-rcudb --force
  only:
    refs:
      - master
    