---
#
# Include the shared gitlab CI definitions
#
include:
  - project: 'enterprisemodules/gitlab_ci'
    file: 'gitlab-ci.yml'

setup RCU:
  stage: acceptance setup
  tags:
    - demo_check
  before_script:
    - mkdir -p modules/software/files
    - cp ~/software/linuxx64_12201_database.zip modules/software/files
  script:
  - vagrant up ml-rcudb
  only:
    refs:
      - master

soa_12213_demo_check:
  extends: .demo_check
  before_script:
    - mkdir -p modules/software/files
    - cp ~/software/jdk-8u161-linux-x64.tar.gz modules/software/files
    - cp ~/software/fmw_12.2.1.3.0_infrastructure.jar modules/software/files
    - cp ~/software/fmw_12.2.1.3.0_soa.jar.zip modules/software/files
    - cp ~/software/jce_policy-8.zip modules/software/files
  script:
    - vagrant up ml-soa12213n1
  after_script:
    - vagrant destroy ml-soa12213n1 --force

soa_12214_demo_check:
  extends: .demo_check
  before_script:
    - mkdir -p modules/software/files
    - cp ~/software/jdk-8u231-linux-x64.tar.gz modules/software/files
    - cp ~/software/fmw_12.2.1.4.0_infrastructure.jar modules/software/files
    - cp ~/software/fmw_12.2.1.4.0_soa.jar.zip modules/software/files
    - cp ~/software/jce_policy-8.zip modules/software/files
  script:
    - vagrant up ml-soa12214n1
  after_script:
    - vagrant destroy ml-soa12214n1 --force

teardown RCU:
  stage: acceptance teardown
  tags:
    - demo_check
  before_script:
    - mkdir -p modules/software/files
    - cp ~/software/linuxx64_12201_database.zip modules/software/files
  script:
  - vagrant destroy ml-rcudb --force
  only:
    refs:
      - master
    